version: '3.3'

services:
  rest-api:
    container_name: rest-api
    image: 'node:14-alpine'
    working_dir: /app
    volumes:
      - ./:/app
      - ./dist:/dist/app:delegated
      - ./node_modules:/app/node_modules:cached
    environment:
      - NODE_ENV=development
      - REST_API_PORT=8080
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=headless
      - DATABASE_PASSWORD=headless
      - DATABASE_NAME=headless
    command: ['npm', 'run', 'start:dev', 'api-rest']
    depends_on: ["database"]
    ports:
      - 8080:8080
  database:
    container_name: database
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_DB: headless
      POSTGRES_USER: headless
      POSTGRES_PASSWORD: headless
    ports:
      - "5432:5432"

